name: PHP Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1]
        laravel: [8.*, 9.*, 10.*]
        exclude:
          - php: 7.4
            laravel: 10.*
          - php: 8.1
            laravel: 8.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip
        coverage: none

    - name: Install dependencies
      run: |
        composer require "illuminate/support:${{ matrix.laravel }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction --no-progress

    - name: Create temp directory
      run: mkdir -p temp/pdf    - name: Execute tests
      run: vendor/bin/phpunit --testsuite=Unit
